#!/usr/bin/env bash

if (($# < 3)); then
    echo "Usage: ${0##*/} username[:passwd_entry] ldaps://host DN -ls [sub-DN] [selector...]"
    echo "or   : ${0##*/} username[:passwd_entry] ldaps://host DN selector..."
    echo
    echo "Lists entries or selects entries from LDAP database. It always does a lexical sort"
    echo "on individual results."
    echo
    echo "Passwords are stored in ~/.pw/<username> files, you can provide a different"
    echo "username than the one stores the password."
    echo "-ls [sub-DN]    lists immediate entries under DN, or it can dial to sub-DN,DN"
    echo "selector...     LDAP query, selector, or any other ldapsearch options"
    exit 1
fi

strategy=sub
sso=${1%:*}
pw=${1#*:}
url=$2
dn=$3
shift 3
if [[ "$1" = "-ls" ]]; then
    if [[ -n "$2" ]]; then
        dn="$2,$dn"
    else
        set -- -ls . .
    fi
    strategy=one
    shift 2
fi

ldapsearch -o ldif-wrap=no -x -D "$sso" -y ~/.pw/"$pw" -H "$url" -s $strategy -b "$dn" -LLL "$@" |
LANG=C awk '{print | cmd; close(cmd); print ""}' RS= cmd=sort
